return {
  leader = " ",
  escape = "jk",
  clear_search_highlighting = "<Esc>",
  move_to_left_window = "<C-h>",
  move_to_down_window = "<C-j>",
  move_to_up_window = "<C-k>",
  move_to_right_window = "<C-l>",
  save_file = "<leader>s",
  open_explorer = "<leader>e",
  next_buffer = "<S-l>",
  previous_buffer = "<S-h>",
  close_buffer = "<S-r>",
  telescope_find_files = "<leader>ff",
  telescope_live_grep = "<leader>fg",
  telescope_buffers = "<leader>fb",
  telescope_help_tags = "<leader>fh",
  lsp_declaration = "gD",
  lsp_definition = "gk",
  lsp_hover = "K",
  lsp_implementation = "gi",
  lsp_signature_help = "<C-k>",
  lsp_add_workspace_folder = "<leader>wa",
  lsp_remove_workspace_folder = "<leader>wr",
  lsp_list_workspace_folders = "<leader>wl",
  lsp_type_definition = "<leader>d",
  lsp_rename = "gn",
  lsp_code_action = "gd",
  lsp_references = "gr",
  lsp_format = "gf",
  trouble_toggle = "<leader>tt",
  trouble_quick_fix = "<leader>tq",
  visual_move_text_down = "J",
  visual_move_text_up = "K",
}

